---
title: "data_pipeline"
author: "Team LSD: Adnan, Jenni, Stephen"
date: "February 26, 2019"
output: 
  html_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(RNHANES)
library(survey)

```


## Load and Merge Data

### PFAS Data and Demographics

```{r load pfas data and demographics}

pfas_data_clean = nhanes_load_data("PFAS_I", "2015-2016", demographics = TRUE) %>% 
  janitor::clean_names() %>% 
  select(seqn, cycle, sddsrvyr, riagendr, ridageyr, 
         ridreth3, dmqmiliz, dmdeduc3, dmdeduc2, wtint2yr,
         wtmec2yr, lbxpfde:lbdmfosl) %>% 
  rename(pfdea = lbxpfde, pfhxs = lbxpfhs, me_pfosa_acoh = lbxmpah,	
         pfna = lbxpfna, pfua = lbxpfua,	pfdoa = lbxpfdo, n_pfoa = lbxnfoa,
         sb_pfoa = lbxbfoa, n_pfos = lbxnfos,	sm_pfos = lbxmfos)

#https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/PFAS_I.htm
#https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DEMO_i.htm

```


### Body Mass Data

```{r load body mass data}

bodymass_data_clean <- nhanes_load_data("BMX_I", "2015-2016", demographics = TRUE) %>% 
  janitor::clean_names() %>% 
  select(seqn, bmxbmi, bmxwt, bmiwt, bmxht,
         bmiht, bmxwaist, bmiwaist, bmxarmc, bmiarmc)

#https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BMX_I.htm

```


### Household Income and Household Education

```{r load income and houshold ed data}

hhincome.edu_data_clean <- nhanes_load_data("DEMO_I", "2015-2016") %>% 
  janitor::clean_names() %>% 
  select(seqn, indhhin2, indfmin2, indfmpir, dmdhredu)

#https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DEMO_i.htm

```


### Diabetes Status

```{r load diabetes data}

diabetes_data_clean <- nhanes_load_data("DIQ_I", "2015-2016") %>% 
  janitor::clean_names() %>% 
  select(seqn, diq010)

#https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DIQ_I.htm

```


### Water Data

Decided not to use water variables because there was completely no association with outcome. 

```{r load water data, include=FALSE}

# Day 1 
#dietary_day1 <- nhanes_load_data("DR1TOT_I", "2015-2016") %>% 
#    select(SEQN, DR1_320Z, DR1_330Z, DR1BWATZ, DR1TWS) %>% 
#  janitor::clean_names() 

# Day 2
#dietary_day2 <- nhanes_load_data("DR2TOT_I", "2015-2016") %>% 
#    select(SEQN, DR2_320Z, DR2_330Z, DR2BWATZ, DR2TWS) %>% 
#  janitor::clean_names()

# Merge 2 dietary recalls
#water_data_clean <- 
#  pfas_data_clean %>% 
#  select(seqn) %>% 
#  left_join(dietary_day1,  by = "seqn") %>% 
#  left_join(dietary_day2,  by = "seqn") %>% 
#  mutate(avg_320z = (dr1_320z + dr2_320z) / 2,
#         avg_330z = (dr1_330z + dr2_320z) / 2,
#         avgbwatz = (dr1bwatz + dr2bwatz) / 2)
         
```


### Merge Data

```{r merge all data}

# Merge all data
aamehs_data = pfas_data_clean %>% 
  left_join(bodymass_data_clean, by = "seqn") %>% 
  left_join(diabetes_data_clean, by = "seqn") %>% 
  left_join(hhincome.edu_data_clean, by = "seqn")

# Clean environment
rm(bodymass_data_clean, pfas_data_clean, hhincome.edu_data_clean, diabetes_data_clean)

```


## Evaluate Missing

```{r evaluate missing}

aamehs_data %>% skimr::skim()

# Drop n=177 who are missing PFAS data
aamehs_data <- aamehs_data %>% 
  filter(n_pfoa != "")

aamehs_data %>% skimr::skim()

# Drop n=16 missing BMI
aamehs_data <- aamehs_data %>% 
  filter(bmxbmi != "")

aamehs_data %>% skimr::skim()
table (aamehs_data$indhhin2, useNA = "ifany") # household income
table (aamehs_data$dmdhredu, useNA = "ifany") # household education
table (aamehs_data$ridreth3, useNA = "ifany") # race/ethnicity - use this!
table (aamehs_data$riagendr, useNA = "ifany") # gender
table (aamehs_data$diq010, useNA = "ifany")   # doc told diabetes
table (aamehs_data$dmqmiliz, useNA = "ifany") # military

# Recode houshold education to move "don't know" to missing (n=2)
aamehs_data$dmdhredu[aamehs_data$dmdhredu == 9] <- NA

# Recode diabetes to move "don't know" to missing (n=2)
aamehs_data$diq010[aamehs_data$diq010 == 9] <- NA

# n=124 missing houshold income --> wont use
# n=71 missing houshold education
# n=2 missing diabetes
# n=229 missing military status
# case complete for race/ethnicity, gender, age

```

## Clean up Variable Names

```{r data cleaning}

aamehs_data <- aamehs_data %>% 
  dplyr::rename(hh_education = dmdhredu,
         race_ethnicity = ridreth3,
         gender = riagendr,
         age = ridageyr,
         diabetes = diq010,
         military = dmqmiliz,
         bmi = bmxbmi,
         weight_kg = bmxwt,
         height_cm = bmxht,
         arm_circ_cm = bmxarmc,
         waist_circ_cm = bmxwaist,
         c_bmiarmc = bmiarmc,
         c_bmiht = bmiht,
         c_bmiwaist = bmiwaist,
         c_bmiwt = bmiwt,
         c_lbdpfdel = lbdpfdel,
         c_lbdpfhsl = lbdpfhsl, 
         c_lbdmpahl = lbdmpahl, 
         c_lbdpfnal = lbdpfnal, 
         c_lbdpfual = lbdpfual, 
         c_lbdpfdol = lbdpfdol,
         c_lbdbfoal = lbdbfoal,
         c_lbdnfoal = lbdnfoal, 
         c_lbdnfosl = lbdnfosl, 
         c_lbdmfosl = lbdmfosl) %>% 
  dplyr::select(-dmdeduc2, -indhhin2, -indfmin2, -cycle, - dmdeduc2, -dmdeduc3, -indfmpir,
                -sddsrvyr) %>% 
  dplyr::mutate(hh_education = as.factor(hh_education),
         diabetes = as.factor(diabetes),
         gender = as.factor(gender),
         race_ethnicity = as.factor(race_ethnicity),
         military = as.factor(military))

skimr::skim(aamehs_data)

```


## Write Out Working Dataset

```{r write out working dataset}

# Save out final dataset
write_csv(aamehs_data, path = "./aamehs_data.csv")

```

