---
title: "rnhanes_nonlinear"
author: "SL"
date: "March 22, 2019"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mgcv)
library(splines)

```

Load dataset from pipeline output
```{r load}
pfas <- read.csv("aamehs_data.csv") %>% 
   select(seqn, gender, age, race_ethnicity, hh_education, diabetes, pfdea, pfhxs, me_pfosa_acoh, pfna, pfua, pfdoa, n_pfoa, sb_pfoa, n_pfos, sm_pfos, bmi) %>% 
  mutate(riagendr = factor(gender),
         ridreth3 = factor(race_ethnicity),
         hh_education = factor(hh_education)) %>% 
  drop_na(bmi)

glimpse(pfas)


#check for missing values
pfas %>% 
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(funs(sum(is.na(.)))) 
```

Missing values: 
indfmpir = 201 
hh_education = 71
bmxbmi = 16


## Linear

### Linear, no additional variables
```{r}
pfoa_linear_single <- lm(bmi ~ n_pfoa, data = pfas)

summary(pfoa_linear_single)

pfoa_linear_single %>% 
  predict(., se.fit = TRUE, type = "terms" ) %>% 
  as.data.frame(.) %>% 
  mutate(pred = n_pfoa) %>% 
  select(pred) %>% 
  bind_cols(pfas) %>% 
  mutate(pred_bmi = pred + mean(bmi)) %>% 
  ggplot(., aes(x = n_pfoa)) + 
    geom_line(aes(y = pred_bmi)) + 
    xlab("n_pfoa") + 
    ylab("Predicted BMI") 



pfos_linear_single <- lm(bmi ~ n_pfos, data = pfas)

summary(pfos_linear_single)


```





### Linear, simple model
```{r pfoa_linear_model}
pfoa_linear <- lm(bmi ~ n_pfoa + gender + age + race_ethnicity + hh_education + diabetes, 
              data = pfas)

summary(pfoa_linear)


pfoa_linear %>% 
  predict(., se.fit = TRUE, type = "terms" ) %>% 
  as.data.frame(.) %>% 
  mutate(pred = fit.n_pfoa) %>% 
  select(pred) %>% 
  bind_cols(pfas) %>% 
  mutate(pred_bmi = pred + mean(bmi)) %>% 
  ggplot(., aes(x = n_pfoa)) + 
    geom_line(aes(y = pred_bmi)) + 
    xlab("n_pfoa") + 
    ylab("Predicted BMI") 


```


```{r pfos_linear}
pfos_linear <- lm(bmi ~ n_pfos + gender + age + race_ethnicity + hh_education + diabetes, 
              data = pfas)

summary(pfos_linear)
```


## Natural Spline Term 

### glm natural spline
```{r pfoa_natural_spline}

ns_pfoa <- lm(bmi ~ ns(n_pfoa, df = 3) + gender + age + race_ethnicity + hh_education + diabetes, data = pfas)

summary(ns_pfoa)
AIC(ns_pfoa)
plot(ns_pfoa)

ns_pfoa %>% 
 predict(., se.fit = TRUE, type = "terms" ) %>% 
 as.data.frame(.) %>% 
  mutate(pred = fit.ns.n_pfoa..df...3.,
         se = se.fit.ns.n_pfoa..df...3.,
         lci = pred - 1.96*se,
         uci = pred + 1.96*se) %>%
  select(pred, se, lci, uci) %>% 
  bind_cols(pfas) %>% 
  mutate(pred_bmi = pred + mean(bmi),
         lci_bmi = lci + mean(bmi),
         uci_bmi = uci + mean(bmi)) %>% 
  ggplot(., aes(n_pfoa)) + 
      geom_line(aes(y = pred_bmi)) + 
      geom_line(aes(y = lci_bmi), color = "darkgrey") + 
      geom_line(aes(y = uci_bmi), color = "darkgrey") + 
      xlab("n_pfoa") + 
      ylab("Predicted BMI (95% CI)") +
      ylim(20,35)




ns_pfos <- lm(bmi ~ ns(n_pfos, df = 3) + gender + age + race_ethnicity + hh_education + diabetes, data = pfas)

summary(ns_pfos)
AIC(ns_pfos)
plot(ns_pfos)

ns_pfos %>% 
 predict(., se.fit = TRUE, type = "terms" ) %>% 
 as.data.frame(.) %>% 
  mutate(pred = fit.ns.n_pfos..df...3.,
         se = se.fit.ns.n_pfos..df...3.,
         lci = pred - 1.96*se,
         uci = pred + 1.96*se) %>%
  select(pred, se, lci, uci) %>% 
  bind_cols(pfas) %>% 
  mutate(pred_bmi = pred + mean(bmi),
         lci_bmi = lci + mean(bmi),
         uci_bmi = uci + mean(bmi)) %>% 
  ggplot(., aes(n_pfos)) + 
      geom_line(aes(y = pred_bmi)) + 
      geom_line(aes(y = lci_bmi), color = "darkgrey") + 
      geom_line(aes(y = uci_bmi), color = "darkgrey") + 
      xlab("n_pfos") + 
      ylab("Predicted BMI (95% CI)") +
      ylim(20,35)


```


### gam natural spline
```{r}

pfos_gam_ns <- gam(bmi ~ ns(n_pfos, df = 3) + gender + age + race_ethnicity + hh_education + diabetes, data = pfas)

termplot(pfos_gam_ns, se = TRUE)

```


## Penalized spline

```{r}
pfoa_ps <- gam(bmi ~ s(n_pfoa) + gender + age + race_ethnicity + hh_education + diabetes, data = pfas)
summary(pfoa_ps)
pfoa_ps$sp   # extract Penalty 
plot(pfoa_ps)


pfoa_ps %>% 
 predict(., se.fit = TRUE, type = "terms" ) %>% 
 as.data.frame(.) %>% 
  mutate(pred = fit.s.n_pfoa.,
         se = se.fit.s.n_pfoa.,
         lci = pred - 1.96*se,
         uci = pred + 1.96*se) %>%
  select(pred, se, lci, uci) %>% 
  bind_cols(pfas) %>% 
  mutate(pred_bmi = pred + mean(bmi),
         lci_bmi = lci + mean(bmi),
         uci_bmi = uci + mean(bmi)) %>% 
  ggplot(., aes(n_pfoa)) + 
      geom_line(aes(y = pred_bmi)) + 
      geom_line(aes(y = lci_bmi), color = "darkgrey") + 
      geom_line(aes(y = uci_bmi), color = "darkgrey") + 
      xlab("n_pfoa") + 
      ylab("Predicted BMI (95% CI)") +
      ylim(20,35)






pfos_ps <- gam(bmi ~ s(n_pfos) + gender + age + race_ethnicity + hh_education + diabetes, data = pfas)
summary(pfos_ps)
pfos_ps$sp   # extract Penalty 
plot(pfos_ps)

pfos_ps %>% 
 predict(., se.fit = TRUE, type = "terms" ) %>% 
 as.data.frame(.) %>% 
  mutate(pred = fit.s.n_pfos.,
         se = se.fit.s.n_pfos.,
         lci = pred - 1.96*se,
         uci = pred + 1.96*se) %>%
  select(pred, se, lci, uci) %>% 
  bind_cols(pfas) %>% 
  mutate(pred_bmi = pred + mean(bmi),
         lci_bmi = lci + mean(bmi),
         uci_bmi = uci + mean(bmi)) %>% 
  ggplot(., aes(n_pfos)) + 
      geom_line(aes(y = pred_bmi)) + 
      geom_line(aes(y = lci_bmi), color = "darkgrey") + 
      geom_line(aes(y = uci_bmi), color = "darkgrey") + 
      xlab("n_pfos") + 
      ylab("Predicted BMI (95% CI)") +
      ylim(20,35)

```










